name: 'NWTC Library module tests'
description: 'Run tests specific to the NWTC Library module'
author: 'Rafael Mudafort https://github.com/rafmudaf'
runs:
  using: "composite"
  steps: 
    - run: |
        source /opt/intel/oneapi/mkl/latest/env/vars.sh
        ctest -VV -R nwtc_library_utest
      working-directory: ${{runner.workspace}}/openfast/build
      shell: bash
